CREATE TABLE users (
	id INTEGER PRIMARY KEY NOT NULL,
	name VARCHAR NOT NULL
);

CREATE TABLE posts (
	id INTEGER PRIMARY KEY NOT NULL,
	title VARCHAR NOT NULL,
	body TEXT,
	user_id INTEGER NOT NULL,
	FOREIGN KEY (user_id)
		REFERENCES users (user_id)
);

CREATE TABLE comments (
	id INTEGER PRIMARY KEY NOT NULL,
	body TEXT NOT NULL,
	post_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	FOREIGN KEY (post_id)
		REFERENCES posts (post_id),
	FOREIGN KEY (user_id)
		REFERENCES users (user_id)
);
